[project]
name = "jupyterlite"
version = "0.9.0"
description = ""
authors = [
    { name = "Pascal Helfenstein", email = "pascal.helfenstein@xemax.ch" },
]
requires-python = "==3.13.5"
readme = "README.md"
dependencies = [
    "jupyterlab-open-url-parameter>=0.3.0",
    "jupyterlite-core>=0.6.4",
    "jupyterlite-pyodide-kernel>=0.6.1",
    "libarchive-c>=5.3",
]

[tool.uv]
package = false

