/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version/app/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App */
        get: operations["app_version_app__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rgb/values/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rgb Values */
        post: operations["rgb_values_v1_rgb_values__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rgb/wipe/{r}/{g}/{b}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rgb Wipe
         * @description Control of the RGB matrix via GET request
         */
        get: operations["rgb_wipe_v1_rgb_wipe__r___g___b___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppVersion */
        AppVersion: {
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RgbMatrixValues
         * @example {
         *       "values": [
         *         [
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           }
         *         ],
         *         [
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           }
         *         ],
         *         [
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           }
         *         ],
         *         [
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           }
         *         ],
         *         [
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           }
         *         ],
         *         [
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           }
         *         ],
         *         [
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           }
         *         ],
         *         [
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           },
         *           {
         *             "b": 0,
         *             "g": 0,
         *             "r": 0
         *           }
         *         ]
         *       ]
         *     }
         */
        RgbMatrixValues: {
            /** Values */
            values: components["schemas"]["RgbPixel"][][];
        };
        /**
         * RgbPixel
         * @example {
         *       "b": 0,
         *       "g": 0,
         *       "r": 0
         *     }
         */
        RgbPixel: {
            /**
             * R
             * @default 0
             */
            r: number;
            /**
             * G
             * @default 0
             */
            g: number;
            /**
             * B
             * @default 0
             */
            b: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    app_version_app__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppVersion"];
                };
            };
        };
    };
    rgb_values_v1_rgb_values__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RgbMatrixValues"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rgb_wipe_v1_rgb_wipe__r___g___b___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                r: number;
                g: number;
                b: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
